# Generated by Django 5.0.14 on 2026-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('codename', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Active', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
